# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panos/development/voronoi-sdl2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panos/development/voronoi-sdl2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panos/development/voronoi-sdl2/CMakeFiles /home/panos/development/voronoi-sdl2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panos/development/voronoi-sdl2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named voronoi

# Build rule for target.
voronoi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 voronoi
.PHONY : voronoi

# fast build rule for target.
voronoi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/build
.PHONY : voronoi/fast

src/draw.o: src/draw.c.o
.PHONY : src/draw.o

# target to build an object file
src/draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/draw.c.o
.PHONY : src/draw.c.o

src/draw.i: src/draw.c.i
.PHONY : src/draw.i

# target to preprocess a source file
src/draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/draw.c.i
.PHONY : src/draw.c.i

src/draw.s: src/draw.c.s
.PHONY : src/draw.s

# target to generate assembly for a file
src/draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/draw.c.s
.PHONY : src/draw.c.s

src/grid.o: src/grid.c.o
.PHONY : src/grid.o

# target to build an object file
src/grid.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/grid.c.o
.PHONY : src/grid.c.o

src/grid.i: src/grid.c.i
.PHONY : src/grid.i

# target to preprocess a source file
src/grid.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/grid.c.i
.PHONY : src/grid.c.i

src/grid.s: src/grid.c.s
.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/grid.c.s
.PHONY : src/grid.c.s

src/init.o: src/init.c.o
.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/init.c.s
.PHONY : src/init.c.s

src/input.o: src/input.c.o
.PHONY : src/input.o

# target to build an object file
src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/input.c.o
.PHONY : src/input.c.o

src/input.i: src/input.c.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/input.c.i
.PHONY : src/input.c.i

src/input.s: src/input.c.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/input.c.s
.PHONY : src/input.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/main.c.s
.PHONY : src/main.c.s

src/seed.o: src/seed.c.o
.PHONY : src/seed.o

# target to build an object file
src/seed.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/seed.c.o
.PHONY : src/seed.c.o

src/seed.i: src/seed.c.i
.PHONY : src/seed.i

# target to preprocess a source file
src/seed.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/seed.c.i
.PHONY : src/seed.c.i

src/seed.s: src/seed.c.s
.PHONY : src/seed.s

# target to generate assembly for a file
src/seed.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/seed.c.s
.PHONY : src/seed.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/util.c.s
.PHONY : src/util.c.s

src/voronoi.o: src/voronoi.c.o
.PHONY : src/voronoi.o

# target to build an object file
src/voronoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/voronoi.c.o
.PHONY : src/voronoi.c.o

src/voronoi.i: src/voronoi.c.i
.PHONY : src/voronoi.i

# target to preprocess a source file
src/voronoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/voronoi.c.i
.PHONY : src/voronoi.c.i

src/voronoi.s: src/voronoi.c.s
.PHONY : src/voronoi.s

# target to generate assembly for a file
src/voronoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/voronoi.dir/build.make CMakeFiles/voronoi.dir/src/voronoi.c.s
.PHONY : src/voronoi.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... voronoi"
	@echo "... src/draw.o"
	@echo "... src/draw.i"
	@echo "... src/draw.s"
	@echo "... src/grid.o"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/seed.o"
	@echo "... src/seed.i"
	@echo "... src/seed.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/voronoi.o"
	@echo "... src/voronoi.i"
	@echo "... src/voronoi.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

